User.create(name: "Eric Davis", title: "Web Developer", email: "eric@email.com", photo: "https://images.timberland.com/is/image/timberland/10061024-HERO?$CATEGORY-LANDING-PRODUCT-REC$")
User.create(name: "Curtis Washington", title: "Software Engineer", email: "curtis@email.com", photo: "https://images.timberland.com/is/image/timberland/10061024-HERO?$CATEGORY-LANDING-PRODUCT-REC$")
User.create(name: "Sandi Metz", title: "Lead Developer", email: "sandi@email.com", photo: "https://images.timberland.com/is/image/timberland/10061024-HERO?$CATEGORY-LANDING-PRODUCT-REC$")
User.create(name: "China Valdez", title: "Lead Recruiter", email: "china@email.com", photo: "https://images.timberland.com/is/image/timberland/10061024-HERO?$CATEGORY-LANDING-PRODUCT-REC$")
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
